package org.eclipse.rcpl;

public enum AlignType {

	NONE, LEFT, CENTER, FILL, GENERAL, CENTER_SELECTION, RIGHT, BOTH, MEDIUM_KASHIDA, DISTRIBUTE, NUM_TAB, HIGH_KASHIDA, LOW_KASHIDA, THAI_DISTRIBUTE, JUST, JUST_LOW, BOTTOM, TOP;

};