<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="wrs" nsURI="http://wrs/1.0" nsPrefix="wrs">
  <eClassifiers xsi:type="ecore:EClass" name="WRS">
    <eOperations name="createIdentity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainvault" lowerBound="1"
        eType="#//Treasury"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supplycontrol" lowerBound="1"
        eType="#//SupplyControl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accounts" lowerBound="1"
        eType="#//Accounts" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="registeredasstets" lowerBound="1"
        eType="#//RegisteredAssets" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="worldeconomy" eType="#//WorldEconomy"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="countries" eType="#//Countries"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" eType="#//Nodes"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="identities" eType="#//Identities"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transactions" eType="#//Transactions"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transactionconditions"
        eType="#//TransactionConditions" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statisticDatas" eType="#//StatisticDatas"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Treasury" eSuperTypes="#//AbstractAccount"/>
  <eClassifiers xsi:type="ecore:EClass" name="TransferVault" eSuperTypes="#//AbstractAccount"/>
  <eClassifiers xsi:type="ecore:EClass" name="Genesis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="treasury" lowerBound="1"
        eType="#//Treasury"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AssetType">
    <eLiterals name="GOLD"/>
    <eLiterals name="SILVER" value="1"/>
    <eLiterals name="CRYPTO" value="2"/>
    <eLiterals name="TRUST" value="3"/>
    <eLiterals name="PHYSICAL" value="4"/>
    <eLiterals name="INTELLECTUAL_PROPERTY" value="5"/>
    <eLiterals name="UDOLLAR" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Asset">
    <eOperations name="register"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assetType" eType="#//AssetType"
        defaultValueLiteral="UDOLLAR"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="materials" upperBound="-1"
        eType="#//Thing"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorldEconomy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nationaleconomies" lowerBound="1"
        upperBound="-1" eType="#//NationalEconomies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NationalEconomies"/>
  <eClassifiers xsi:type="ecore:EClass" name="Country">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fiatcurrency" lowerBound="1"
        eType="#//FiatCurrency" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nationaleconomies" eType="#//NationalEconomies"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regions" upperBound="-1"
        eType="#//CountryRegion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FiatCurrency"/>
  <eClassifiers xsi:type="ecore:EClass" name="Identity" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="UUID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Thing" eSuperTypes="#//Identity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongsTo" eType="#//Identity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Individual" eSuperTypes="#//Identity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="worksFor" upperBound="-1"
        eType="#//LegalEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="legalPartnerOf" upperBound="-1"
        eType="#//LegalEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegalEntity" eSuperTypes="#//Identity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//LegalEntityType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Account" eSuperTypes="#//AbstractAccount">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupplyControl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="genesis" lowerBound="1"
        eType="#//Genesis"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Accounts">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//AbstractAccount" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transaction" eSuperTypes="#//AbstractTransaction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assets" eType="#//Asset"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transactions" upperBound="-1"
        eType="#//AbstractAccount"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegisteredAssets">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Asset" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractAccount">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assets" upperBound="-1"
        eType="#//Asset"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transaction" eType="#//Transaction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongsTo" eType="#//Identity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransactionCollection" eSuperTypes="#//AbstractTransaction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="networkengine" lowerBound="1"
        eType="#//NetworkEngine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkEngine"/>
  <eClassifiers xsi:type="ecore:EClass" name="Countries">
    <eStructuralFeatures xsi:type="ecore:EReference" name="country" eType="#//Country"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Nodes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identities">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Identity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transactions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//AbstractTransaction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTransaction"/>
  <eClassifiers xsi:type="ecore:EEnum" name="LegalEntityType">
    <eLiterals name="COMPANY"/>
    <eLiterals name="ACCOUNTANT" value="1"/>
    <eLiterals name="CHARITY" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeAccount" eSuperTypes="#//AbstractAccount"/>
  <eClassifiers xsi:type="ecore:EClass" name="TransactionConditions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//TransactionCondition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransactionCondition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formula" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signedInputs" upperBound="-1"
        eType="#//SignedInput" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SignedInput">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="identity" eType="#//Identity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//InputValueType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InputValueType">
    <eLiterals name="DATE"/>
    <eLiterals name="NUMBER" value="1"/>
    <eLiterals name="BOOLEAN" value="2"/>
    <eLiterals name="TEXT" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statistics"/>
  <eClassifiers xsi:type="ecore:EClass" name="StatisticDatas">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" eType="#//Statistics"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CountryRegion"/>
</ecore:EPackage>
