<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="worldreservesystem" nsURI="http://www.example.org/worldreservesystem"
    nsPrefix="worldreservesystem">
  <eClassifiers xsi:type="ecore:EClass" name="WorldReserveSystem" eSuperTypes="#//Identity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transfervaults" lowerBound="1"
        eType="#//TransferVaults" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainvault" lowerBound="1"
        eType="#//MainVault" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="identities" lowerBound="1"
        eType="#//Identities" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supplycontrol" lowerBound="1"
        eType="#//SupplyControl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wallets" lowerBound="1"
        eType="#//Wallets" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="registeredasstets" lowerBound="1"
        eType="#//RegisteredAsstets"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MainVault" eSuperTypes="#//AbstractVault"/>
  <eClassifiers xsi:type="ecore:EClass" name="TransferVault" eSuperTypes="#//AbstractVault"/>
  <eClassifiers xsi:type="ecore:EClass" name="TransferVaults">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="New documentation note"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//TransferVault" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Genesis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainvault" lowerBound="1"
        eType="#//MainVault"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AssetType">
    <eLiterals name="GOLD"/>
    <eLiterals name="SILVER" value="1"/>
    <eLiterals name="CRYPTO" value="2"/>
    <eLiterals name="UDOLLAR" value="3"/>
    <eLiterals name="MATERIAL" value="4"/>
    <eLiterals name="INTELLECTUAL_PROPERTY" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Asset">
    <eOperations name="register"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assetType" eType="#//AssetType"
        defaultValueLiteral="UDOLLAR"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="materials" upperBound="-1"
        eType="#//Material"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorldEconomy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nationaleconomies" lowerBound="1"
        eType="#//NationalEconomies" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NationalEconomies">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Nation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Nation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fiatcurrency" lowerBound="1"
        eType="#//FiatCurrency" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FiatCurrency"/>
  <eClassifiers xsi:type="ecore:EClass" name="Accountants">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Accountant" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Accountant"/>
  <eClassifiers xsi:type="ecore:EClass" name="Identity" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="UUID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Material" eSuperTypes="#//Identity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongsTo" eType="#//Identity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Individual" eSuperTypes="#//Identity"/>
  <eClassifiers xsi:type="ecore:EClass" name="LegalEntity" eSuperTypes="#//Identity"/>
  <eClassifiers xsi:type="ecore:EClass" name="NewEClass17"/>
  <eClassifiers xsi:type="ecore:EClass" name="Identities">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Identity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wallet" eSuperTypes="#//AbstractVault">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongsTo" eType="#//Identity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupplyControl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="genesis" lowerBound="1"
        eType="#//Genesis"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wallets">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Wallet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transaction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assets" eType="#//Asset"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//AbstractVault"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//AbstractVault"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegisteredAsstets">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Asset"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractVault">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assets" upperBound="-1"
        eType="#//Asset"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransactionCollection"/>
</ecore:EPackage>
