<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rcpl" nsURI="http://rcpl/1.0" nsPrefix="rcpl">
  <eClassifiers xsi:type="ecore:EEnum" name="ToolType">
    <eLiterals name="BUTTON"/>
    <eLiterals name="TOGGLEBUTTON" value="1"/>
    <eLiterals name="TEXTFIELD" value="2"/>
    <eLiterals name="PASSWORDFIELD" value="3"/>
    <eLiterals name="DATEFIELD" value="4"/>
    <eLiterals name="DATEANDTIMEFIELD" value="5"/>
    <eLiterals name="SPLITMENUBUTTON" value="6"/>
    <eLiterals name="RADIOBUTTON" value="7"/>
    <eLiterals name="CHECKBOX" value="8"/>
    <eLiterals name="COMBO" value="9"/>
    <eLiterals name="NAVIGATOR" value="10"/>
    <eLiterals name="COLOR_CHOOSER" value="11"/>
    <eLiterals name="OTHER" value="12"/>
    <eLiterals name="CHOICEBOX" value="13"/>
    <eLiterals name="HTMLEDITOR" value="14"/>
    <eLiterals name="HYPERLINK" value="15"/>
    <eLiterals name="IMAGEVIEW" value="16"/>
    <eLiterals name="LABEL" value="17"/>
    <eLiterals name="LISTVIEW" value="18"/>
    <eLiterals name="SEPARATOR_VERTICAL" value="19"/>
    <eLiterals name="MENUBAR" value="20"/>
    <eLiterals name="SEPARATOR_HORIZONTAL" value="21"/>
    <eLiterals name="PROGRESSINDICATOR" value="22"/>
    <eLiterals name="PROGRESSBAR" value="23"/>
    <eLiterals name="MENUBUTTON" value="24"/>
    <eLiterals name="WEBVIEW" value="25"/>
    <eLiterals name="TEXTAREA" value="26"/>
    <eLiterals name="SLIDER_VERTICAL" value="27"/>
    <eLiterals name="SLIDER_HORIZONTAL" value="28"/>
    <eLiterals name="GRIDPANE" value="29"/>
    <eLiterals name="FLOWPANE" value="30"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FontStyles">
    <eLiterals name="NORMAL" value="2"/>
    <eLiterals name="BOLD"/>
    <eLiterals name="ITALIC" value="1"/>
    <eLiterals name="UNDERLINE" value="3"/>
    <eLiterals name="UNDERLINE_2" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ToolBarReplacementPolicy">
    <eLiterals name="REPLACE_ALL"/>
    <eLiterals name="ADD" value="1"/>
    <eLiterals name="REPLACE_ALL_MATCHES" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GroupType">
    <eLiterals name="ACCORDIONITEM"/>
    <eLiterals name="GRIDPANE" value="1"/>
    <eLiterals name="FLOWPANE" value="2"/>
    <eLiterals name="ANCHORPANE" value="3"/>
    <eLiterals name="ACCORDION" value="4"/>
    <eLiterals name="BORDERPANE" value="5"/>
    <eLiterals name="HBOX" value="6"/>
    <eLiterals name="VBOX" value="7"/>
    <eLiterals name="PANE" value="8"/>
    <eLiterals name="SCROLLPANE" value="9"/>
    <eLiterals name="HORIZONTALSPLITPANE" value="10"/>
    <eLiterals name="VERTICALSPLITPANE" value="11"/>
    <eLiterals name="STACKPANE" value="12"/>
    <eLiterals name="TAB" value="13"/>
    <eLiterals name="TABPANE" value="14"/>
    <eLiterals name="TILEPANE" value="15"/>
    <eLiterals name="TITLEDPANE" value="16"/>
    <eLiterals name="TOOLBAR" value="17"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Layoutable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutX" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toolTip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="createDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beginDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="leaf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RCPL" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allPlugins" lowerBound="1"
        eType="#//Plugins" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allPerspectives" lowerBound="1"
        eType="#//Perspectives" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allPreferences" lowerBound="1"
        eType="#//Preferences" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allTools" lowerBound="1"
        eType="#//Tools" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allFavorites" eType="#//Favorites"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versionMajor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versionMinor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versionMaintenance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="buildNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versionDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allResources" eType="#//Resources"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allPersons" eType="#//Persons"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkedRcpls" upperBound="-1"
        eType="#//RCPL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Perspectives" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Perspective" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Perspective" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sideToolBar" lowerBound="1"
        eType="#//SideToolBar" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topToolBar" lowerBound="1"
        eType="#//TopToolBar" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="quickToolBar" lowerBound="1"
        eType="#//QuickToolBar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="quickTools" lowerBound="1"
        eType="#//QuickTools" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Preference" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Logins" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Login" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Login" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="country" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rcpl" eType="#//RCPL" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="person" eType="#//Person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domains" upperBound="-1"
        eType="#//Domain"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Favorites" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" lowerBound="1"
        upperBound="-1" eType="#//FavoritesGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultSetId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Favorite" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="link" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="URI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="URL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentCreationDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rating" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastUsedDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showOnToolBar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FavoritesGroup" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1"
        eType="#//FavoritesGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="favorites" upperBound="-1"
        eType="#//Favorite" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkedFavorites" upperBound="-1"
        eType="#//Favorite"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Preferences" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//PreferenceGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="system" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plugins" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Plugin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plugin" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bundleId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roles" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="users" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="groups" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPerspective" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readOnly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultPerspective" lowerBound="1"
        eType="#//Perspective"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="perspectives" upperBound="-1"
        eType="#//Perspective"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTool" abstract="true" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gridX" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gridY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="spanX" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="spanY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labeled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="notImplemented" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="service" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tool" eSuperTypes="#//AbstractTool">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ToolType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToolGroup" eSuperTypes="#//AbstractTool">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toolGroups" upperBound="-1"
        eType="#//ToolGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="grid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tools" upperBound="-1"
        eType="#//Tool" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//GroupType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tools" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toolgroupChildren" upperBound="-1"
        eType="#//ToolGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toolChildren" upperBound="-1"
        eType="#//Tool" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuickTools" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="quickTools" upperBound="-1"
        eType="#//ToolGroup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopToolBar" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toolGroups" upperBound="-1"
        eType="#//ToolGroup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SideToolBar" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toolGroups" upperBound="-1"
        eType="#//ToolGroup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuickToolBar" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toolGroups" upperBound="-1"
        eType="#//ToolGroup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Folder" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="folders" upperBound="-1"
        eType="#//Folder" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkedResources" upperBound="-1"
        eType="#//Resource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="template" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkedResources" upperBound="-1"
        eType="#//Resource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainPerspective" eType="#//Perspective"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="middleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="addresses" upperBound="-1"
        eType="#//Address"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonGroup" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="persongroups" upperBound="-1"
        eType="#//PersonGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="persons" upperBound="-1"
        eType="#//Person" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkedPersons" upperBound="-1"
        eType="#//Person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkedPersongroups" upperBound="-1"
        eType="#//PersonGroup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resources" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Folder" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreferenceGroup" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferences" upperBound="-1"
        eType="#//Preference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkedPreferences" upperBound="-1"
        eType="#//Preference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferencegroups" upperBound="-1"
        eType="#//PreferenceGroup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Persons" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//PersonGroup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RCPLTemplates" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//RCPL" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JPerson" eSuperTypes="#//Person"/>
  <eClassifiers xsi:type="ecore:EClass" name="NPerson" eSuperTypes="#//Person"/>
  <eClassifiers xsi:type="ecore:EClass" name="Address" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="country" eType="#//Country"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="city" eType="#//City"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="street" eType="#//Street"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="housenumber" upperBound="-1"
        eType="#//HouseNumber"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="buildings" upperBound="-1"
        eType="#//Building"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="addressType" eType="#//AddressType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Country" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cities" upperBound="-1"
        eType="#//City" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="worldregions" upperBound="-1"
        eType="#//WorldRegion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="City" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="streets" upperBound="-1"
        eType="#//Street" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Geo" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="countries" upperBound="-1"
        eType="#//Country" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="worldregions" upperBound="-1"
        eType="#//WorldRegion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorldRegion" eSuperTypes="#//Layoutable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Street" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="housenumbers" upperBound="-1"
        eType="#//HouseNumber" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="buildings" upperBound="-1"
        eType="#//Building" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HouseNumber" eSuperTypes="#//Layoutable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Building" eSuperTypes="#//Layoutable"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AddressType">
    <eLiterals name="RESIDENCE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contact" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="phones" upperBound="-1"
        eType="#//Phone" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Phone" eSuperTypes="#//Layoutable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Domains">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Domain" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Domain">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="host" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
